version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Installing SAM CLI"
      - pip install aws-sam-cli
      - echo "SAM CLI installed"
      - echo "Current directory:" && pwd
      - ls -al
      - sam build -t template.yml
      - echo "Pipeline bucket name $ArtifactBucket"
      - sam package --s3-bucket $ArtifactBucket --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml

