version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - mkdir package
      - cp lambda_function.py package/
      - cd package && zip function.zip lambda_function.py && cd ..
      - mv package/function.zip .
artifacts:
  files:
    - template.yaml
    - function.zip
